name: evtol
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy>=1.24
  - scipy>=1.10
  - networkx>=3.0
  - shapely>=2.0
  - pyproj>=3.5
  - pydantic>=2.5
  - pyyaml>=6.0
  - pip:
      - loguru>=0.7
      - pytest>=7.4
      - typing-extensions>=4.9
      - black==24.3.0
      - ruff==0.6.2
      - isort==5.13.2
      - mypy==1.10.0
      - pre-commit==3.7.1

