crs:
  working: "EPSG:4326"

resolution:
  base_meter: 2.0

routing:
  allow_alternatives: true
  num_alternatives: 3
  grid_resolution_deg: 0.01

cost_weights:
  distance: 0.3
  energy: 0.3
  risk: 0.3
  time: 0.1

constraints:
  max_altitude_m: 500.0
  min_altitude_m: 50.0

perception:
  mode: "fake"  # use lightweight fake perception to avoid external deps during demo
  defaults:
    feasible: true
    energy_cost_kwh_per_km: 0.8
    risk_score: 0.2

