# Default configuration for eVTOL Trajectory Optimization System

# System settings
debug: false
log_level: "INFO"
max_workers: 4

# Data paths
data_root: "data"
raw_data_path: "data/0_raw"
processed_data_path: "data/1_processed"
derived_data_path: "data/2_derived"

# Cache settings
cache_enabled: true
cache_size: 1000

# API settings
api_host: "localhost"
api_port: 8000
api_timeout: 30.0

# Perception layer configuration
perception:
  terrain:
    resolution: 1.0  # meters
    max_height: 1000.0  # meters
    interpolation_method: "bilinear"
  
  weather:
    update_interval: 300  # seconds
    forecast_hours: 24
  
  threats:
    detection_range: 5000.0  # meters
    update_frequency: 1.0  # Hz
  
  fusion:
    confidence_threshold: 0.7
    max_age: 30.0  # seconds

# Planning layer configuration
planning:
  routing:
    algorithm: "astar"
    heuristic: "euclidean"
    max_iterations: 10000
  
  optimization:
    max_iterations: 1000
    convergence_tolerance: 1e-6
    population_size: 50
  
  constraints:
    max_altitude: 1000.0  # meters
    min_altitude: 10.0  # meters
    max_speed: 50.0  # m/s
    max_acceleration: 5.0  # m/s²
  
  robust:
    uncertainty_margin: 0.1
    monte_carlo_samples: 100

# Vehicle layer configuration
vehicle:
  dynamics:
    integration_method: "rk4"
    time_step: 0.01  # seconds
    max_simulation_time: 3600.0  # seconds
  
  energy:
    battery_capacity: 100.0  # kWh
    charging_efficiency: 0.9
    discharge_efficiency: 0.95
  
  actuators:
    motor_max_rpm: 10000
    esc_response_time: 0.01  # seconds
  
  constraints:
    max_payload: 100.0  # kg
    max_flight_time: 3600.0  # seconds

# Control layer configuration
control:
  flight_controller:
    control_frequency: 100.0  # Hz
    pid_gains:
      roll:
        kp: 1.0
        ki: 0.1
        kd: 0.01
      pitch:
        kp: 1.0
        ki: 0.1
        kd: 0.01
      yaw:
        kp: 1.0
        ki: 0.1
        kd: 0.01
  
  trajectory_generator:
    smoothing_factor: 0.1
    max_curvature: 0.1  # 1/meters
    waypoint_tolerance: 5.0  # meters


