# Development configuration for eVTOL Trajectory Optimization System

# System settings
debug: true
log_level: "DEBUG"
max_workers: 2

# Data paths
data_root: "data"
raw_data_path: "data/0_raw"
processed_data_path: "data/1_processed"
derived_data_path: "data/2_derived"

# Cache settings
cache_enabled: true
cache_size: 100

# API settings
api_host: "localhost"
api_port: 8001
api_timeout: 60.0

# Perception layer configuration
perception:
  terrain:
    resolution: 5.0  # meters (lower resolution for development)
    max_height: 500.0  # meters
    interpolation_method: "nearest"
  
  weather:
    update_interval: 60  # seconds (more frequent updates)
    forecast_hours: 6
  
  threats:
    detection_range: 2000.0  # meters (smaller range for development)
    update_frequency: 0.5  # Hz
  
  fusion:
    confidence_threshold: 0.5  # Lower threshold for development
    max_age: 60.0  # seconds

# Planning layer configuration
planning:
  routing:
    algorithm: "astar"
    heuristic: "manhattan"  # Simpler heuristic for development
    max_iterations: 1000  # Fewer iterations for faster development
  
  optimization:
    max_iterations: 100  # Fewer iterations for development
    convergence_tolerance: 1e-4
    population_size: 20  # Smaller population for development
  
  constraints:
    max_altitude: 500.0  # meters (lower for development)
    min_altitude: 5.0  # meters
    max_speed: 25.0  # m/s (slower for development)
    max_acceleration: 2.0  # m/s²
  
  robust:
    uncertainty_margin: 0.2  # Higher margin for development
    monte_carlo_samples: 20  # Fewer samples for development

# Vehicle layer configuration
vehicle:
  dynamics:
    integration_method: "euler"  # Simpler integration for development
    time_step: 0.05  # seconds (larger time step for development)
    max_simulation_time: 600.0  # seconds (shorter for development)
  
  energy:
    battery_capacity: 50.0  # kWh (smaller for development)
    charging_efficiency: 0.8
    discharge_efficiency: 0.9
  
  actuators:
    motor_max_rpm: 5000  # Lower RPM for development
    esc_response_time: 0.02  # seconds (slower response for development)
  
  constraints:
    max_payload: 50.0  # kg (smaller payload for development)
    max_flight_time: 1800.0  # seconds (shorter for development)

# Control layer configuration
control:
  flight_controller:
    control_frequency: 50.0  # Hz (lower frequency for development)
    pid_gains:
      roll:
        kp: 0.5  # Lower gains for development
        ki: 0.05
        kd: 0.005
      pitch:
        kp: 0.5
        ki: 0.05
        kd: 0.005
      yaw:
        kp: 0.5
        ki: 0.05
        kd: 0.005
  
  trajectory_generator:
    smoothing_factor: 0.2  # More smoothing for development
    max_curvature: 0.05  # 1/meters (gentler curves for development)
    waypoint_tolerance: 10.0  # meters (larger tolerance for development)


