# Production configuration for eVTOL Trajectory Optimization System

# System settings
debug: false
log_level: "WARNING"
max_workers: 8

# Data paths
data_root: "/data/evtol"
raw_data_path: "/data/evtol/raw"
processed_data_path: "/data/evtol/processed"
derived_data_path: "/data/evtol/derived"

# Cache settings
cache_enabled: true
cache_size: 10000

# API settings
api_host: "0.0.0.0"
api_port: 8000
api_timeout: 10.0

# Perception layer configuration
perception:
  terrain:
    resolution: 0.5  # meters (high resolution for production)
    max_height: 2000.0  # meters
    interpolation_method: "cubic"
  
  weather:
    update_interval: 600  # seconds (less frequent updates for production)
    forecast_hours: 48
  
  threats:
    detection_range: 10000.0  # meters (larger range for production)
    update_frequency: 2.0  # Hz
  
  fusion:
    confidence_threshold: 0.8  # Higher threshold for production
    max_age: 15.0  # seconds (shorter age for production)

# Planning layer configuration
planning:
  routing:
    algorithm: "astar"
    heuristic: "euclidean"
    max_iterations: 50000  # More iterations for production
  
  optimization:
    max_iterations: 5000  # More iterations for production
    convergence_tolerance: 1e-8
    population_size: 100  # Larger population for production
  
  constraints:
    max_altitude: 2000.0  # meters (higher for production)
    min_altitude: 20.0  # meters
    max_speed: 100.0  # m/s (faster for production)
    max_acceleration: 10.0  # m/s²
  
  robust:
    uncertainty_margin: 0.05  # Tighter margin for production
    monte_carlo_samples: 500  # More samples for production

# Vehicle layer configuration
vehicle:
  dynamics:
    integration_method: "rk4"
    time_step: 0.001  # seconds (smaller time step for production)
    max_simulation_time: 7200.0  # seconds (longer for production)
  
  energy:
    battery_capacity: 200.0  # kWh (larger for production)
    charging_efficiency: 0.95
    discharge_efficiency: 0.98
  
  actuators:
    motor_max_rpm: 15000  # Higher RPM for production
    esc_response_time: 0.005  # seconds (faster response for production)
  
  constraints:
    max_payload: 200.0  # kg (larger payload for production)
    max_flight_time: 7200.0  # seconds (longer for production)

# Control layer configuration
control:
  flight_controller:
    control_frequency: 200.0  # Hz (higher frequency for production)
    pid_gains:
      roll:
        kp: 2.0  # Higher gains for production
        ki: 0.2
        kd: 0.02
      pitch:
        kp: 2.0
        ki: 0.2
        kd: 0.02
      yaw:
        kp: 2.0
        ki: 0.2
        kd: 0.02
  
  trajectory_generator:
    smoothing_factor: 0.05  # Less smoothing for production
    max_curvature: 0.2  # 1/meters (sharper curves for production)
    waypoint_tolerance: 2.0  # meters (tighter tolerance for production)


